version: "3.8"

services:

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql/"
      - "./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "testing"

volumes:
  db-data:
